# Generated by Django 4.2.4 on 2023-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preparation",
            name="code",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
