# Generated by Django 4.2.4 on 2023-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_preparation_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mixing",
            name="type",
        ),
        migrations.AddField(
            model_name="mixing",
            name="pattern",
            field=models.CharField(
                blank=True,
                choices=[("C", "Circular"), ("X", "Cross"), ("L", "Linear")],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mixing",
            name="tool",
            field=models.CharField(
                blank=True,
                choices=[("S", "Spatula"), ("F", "Flask"), ("P", "Pestle")],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
