# Generated by Django 4.2.4 on 2023-08-25 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0003_remove_mixing_type_mixing_pattern_mixing_tool"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mixing",
            new_name="Action",
        ),
        migrations.RemoveField(
            model_name="preparation",
            name="container",
        ),
        migrations.RemoveField(
            model_name="preparation",
            name="grid",
        ),
        migrations.RemoveField(
            model_name="preparation",
            name="mixing",
        ),
    ]
