# Generated by Django 4.2.4 on 2023-08-25 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_rename_mixing_action_remove_preparation_container_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="type",
        ),
        migrations.RemoveField(
            model_name="grid",
            name="type",
        ),
    ]
