# Generated by Django 4.2.4 on 2023-08-29 09:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_container_type_remove_grid_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="grid",
            name="keywords",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=50),
                blank=True,
                default=None,
                max_length=1019,
                null=True,
                size=20,
            ),
        ),
    ]
